version: '3.3'
services:
    appserver:
        build:
            context: ./docker/golang
        container_name: tweat-appserver
        tty: true
        environment:
            - MYSQL_TWEAT_USER=tweat
            - MYSQL_TWEAT_PASSWORD=tweat
            - MYSQL_TWEAT_HOST=db
            - MYSQL_TWEAT_PORT=3306
            - MYSQL_TWEAT_DATABASE=tweat
        ports:
            - 3000:3000
        volumes:
            - ./:/app
    db:
        image: mysql:8.0
        container_name: tweat-db
        command: mysqld --user=root
        tty: true
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=tweat
            - MYSQL_USER=tweat
            - MYSQL_PASSWORD=tweat
            - MYSQL_DATABASE=tweat
        volumes:
            - ./data:/data
            - ./database/sql:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
